name: Java CI

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: |
          # mvn -B compile
          mvn package

      - name: Find
        run: |
          ls -lhAR .build
          mv -v .build/mkimg*.jar bin/mkimg.jar
          ls -lhAR bin

      - name: Run
        run: |
          sh bin/mkimg.sh src -o /tmp/img.udf

      # - name: Run tests
      #   run: mvn -B test
